"""models

Revision ID: 747681ad296d
Revises: 
Create Date: 2020-09-23 01:02:05.531119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747681ad296d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.Binary(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('wallets',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('funds', sa.BigInteger(), nullable=True),
    sa.Column('owner_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('transactions',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('from_wallet_uid', sa.Integer(), nullable=True),
    sa.Column('to_wallet_uid', sa.Integer(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_wallet_uid'], ['wallets.uid'], ),
    sa.ForeignKeyConstraint(['to_wallet_uid'], ['wallets.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('wallets')
    op.drop_table('users')
    # ### end Alembic commands ###
